name: food_client
description: A client for hello fresh recipes

publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: ">=3.13.4 <4.0.0"
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.5.3
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  commons_graphql:
    path: ../commons_graphql
  cupertino_icons: ^1.0.2
  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git
      ref: flutter-3.7
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_riverpod: ^2.3.6
  fpdart: ^0.3.0
  freezed_annotation: ^2.0.3
  go_router: ^10.1.0
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.6.0
  logger: ^2.0.2+1
  logging: ^1.1.0
  mockito: ^5.4.1
  path_provider: ^2.0.11
  retrofit: ^3.3.1
  riverpod_annotation: ^2.1.1
  share_plus: ^6.3.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  hive_generator: ^2.0.1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
